[package]
name = "bytecore"
version = "0.1.1"
edition = "2024"
description = "A Chip-8 emulator virtual machine built in Rust"
authors = ["CompileRider"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/CompileRider/Bytecore.git"
keywords = ["emulator", "chip8", "retro", "gaming"]
categories = ["emulators", "games"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
thiserror = "2.0"
bitflags = "2.13.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
sdl2 = { version = "0.38.0", optional = true }
ratatui = { version = "0.30.2", optional = true }
crossterm = { version = "0.29.0", optional = true }

[features]
default = ["terminal"]
sdl2 = ["dep:sdl2"]
terminal = ["dep:ratatui", "dep:crossterm"]

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
